# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
