# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_image/no_profile.jpg', height_field=150, upload_to='profile_image', width_field=150),
        ),
    ]
