# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170629_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='width',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_image/no_profile.jpg', height_field='height', upload_to='profile_image', width_field='width'),
        ),
    ]
