# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170629_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='no_profile.jpg', upload_to='profile_image'),
        ),
    ]
