# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170629_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test_field',
            field=models.CharField(default='', max_length=30),
        ),
    ]
