# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='test_field',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_image/no_profile.jpg', upload_to='profile_image/'),
        ),
    ]
