# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_in_touch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.PositiveSmallIntegerField(choices=[(1, "I can't log in"), (2, "I can't sign up"), (3, "I can't pay for account"), (4, 'Another (I will write it)')])),
                ('user', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
