# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpassword',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_password_to_game', to='products.Game'),
        ),
        migrations.AddField(
            model_name='loginpassword',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_password_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
