# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='pages',
        ),
        migrations.AddField(
            model_name='game',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
