# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 14:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='auction_bid',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
