# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170707_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['publication_date']},
        ),
    ]
