# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170705_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='book_type',
            new_name='game_type',
        ),
    ]
