# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-publication_date']},
        ),
    ]
