# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170705_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['publication_date']},
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
    ]
