# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170718_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['publication_date']},
        ),
    ]
