# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 00:12
from __future__ import unicode_literals

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170718_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
